apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mef
  labels:
    app: backend
    component: api
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
