apiVersion: v1
kind: ConfigMap
metadata:
  name: mef-config
  namespace: mef
data:
  # Database Configuration
  DB_NAME: "mef_db"
  DB_USER: "mef_user"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"

  # Backend Configuration
  NODE_ENV: "production"
  BACKEND_PORT: "3000"

  # Morpheus/Triton Configuration
  MORPHEUS_PORT: "8000"
  MORPHEUS_SERVICE_URL: "http://morpheus-triton-service:8000"

  # PostgreSQL Configuration
  PGDATA: "/var/lib/postgresql/data/pgdata"
