apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mef
  labels:
    app: frontend
    component: ui
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
