apiVersion: apps/v1
kind: Deployment
metadata:
  name: morpheus-triton
  namespace: mef
  labels:
    app: morpheus-triton
    component: ml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: morpheus-triton
  template:
    metadata:
      labels:
        app: morpheus-triton
        component: ml-service
    spec:
      containers:
      - name: morpheus-triton
        image: mef-morpheus:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mef-config
              key: MORPHEUS_PORT
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
