apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ai-platform
  labels:
    app: backend
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: backend
