apiVersion: apps/v1
kind: Deployment
metadata:
  name: morpheus-triton
  namespace: ai-platform
  labels:
    app: morpheus-triton
    component: ml-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: morpheus-triton
  template:
    metadata:
      labels:
        app: morpheus-triton
        component: ml-model
    spec:
      containers:
      - name: morpheus-triton
        image: morpheus-triton:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PORT
          value: "8000"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
            # nvidia.com/gpu: 1  # Uncomment if GPU is available
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
